#이 파일은 개발 시 사용하는 파일, 배포용 설정은 github secret에 존재하며 github action을 통해 포함
#TODO profiles 설정을 하면 db가 연결되지 않는 문제가 있음
spring:
    #config:
        #activate:
            #on-profile: dev

    origin: http://localhost:8080

    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: sa

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true




jwt:
    accessToken:
        tokenPrefix: 'Bearer '
        GettingHeaderName: 'Authorization'
        SendingHeaderName: 'accessToken'
        secret: 'KEWordsSecretAccessKey'
        #expirationMs: 900000 # 1000 * 60 * 15 -> 15 minutes
        expirationMs: 10000 # 1000 * 10 -> 10 seconds for test
    refreshToken:
        headerName: 'refreshToken'
        secret: 'KEWordsSecretRefreshKey'
        expirationMs: 1209600000 # 1000 * 60 * 60 * 24 * 14 -> 2 weeks

Cors:
    AllowedOriginPatterns: '*'
    AllowedHeaders: '*'
    AllowedMethods: '*'



debug: true