#이 파일은 개발 시 사용하는 파일, 배포용 설정은 github secret에 존재하며 github action을 통해 포함
#TODO profiles 설정을 하면 db가 연결되지 않는 문제가 있음
spring:
    #config:
        #activate:
            #on-profile: dev

    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: sa

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true




#TODO github secret에 갱신해야함
jwt:
    accessToken:
        tokenPrefix: 'Bearer '
        headerName: 'Authorization'
        secret: 'KEWordsSecretAccessKey'
        expirationMs: 900000 # 1000 * 60 * 15 -> 15 minutes
    refreshToken:
        headerName: 'refreshToken'
        secret: 'KEWordsSecretRefreshKey'
        expirationMs: 1209600000 # 1000 * 60 * 60 * 24 * 14 -> 2 weeks

#debug: true